### ISSUE TITLE
build broke with Playready 3.3 without Netflix extension

### ISSUE THREAD

**Issue by moorthy-bs** [WebPlatformForEmbedded/OCDM-Playready#26] opened 2020-01-27 07:32 UTC
wpeframework-ocdm-playready build broke when building with Playready 3.3 without Netflix extension (-DNETFLIX_EXTENSION=OFF). Found some regression in the recent commit [f75e05](https://github.com/WebPlatformForEmbedded/OCDM-Playready/commit/f75e0558dd2d1b3f7bb0f7b8bfd12eb10809d647) which is made to work Netflix decryption where some of the mandatory variables are removed which supports PlayReady 3.3.

Changes that affecting Playready 3.3
1. `DRM_DWORD rgdwMappings[2]` is removed which is used on 3.3 (Line no. #L599-#L602)
2. Input arguments validations are removed on Decrypt() function.
3. `Drm_Reader_InitDecrypt()` is implemented under `#ifndef PR_3_3` and now the preprocessor macro is removed. InitDecrypt() is not available on 3.3
4. ChkDR() is a macro that comes with Playready headers that uses `ErrorExit` label on 3.3 which is again introduced in `Drm_Reader_DecryptOpaque`
5. Decrypt Context is the first argument to `Drm_Reader_DecryptOpaque` which is a pointer as per the spec. Passing double pointer is a bug and this is already discussed in a pull request [#15](https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/15#discussion_r342534015)
6. `oAESContext` is no where defined but used in `Drm_Reader_DecryptOpaque` (may be extern in netflix extension headers)

There is a pre-processor macro `PR_3_3`, will be defined only for Playready 3.3 and code to support this version implemented under that. We understand that Netflix decryption is based on Playready 3.3 as changes [f75e05](https://github.com/WebPlatformForEmbedded/OCDM-Playready/commit/f75e0558dd2d1b3f7bb0f7b8bfd12eb10809d647) made on Drm_Reader_DecryptOpaque but also it should support PR 3.3 without Netflix extension.

**Comment by moorthy-bs** [comment] 2020-01-27 07:40
This should be fixed by supporting both Playready 3.3 with and without Netflix extension.

**Comment by petegriffin** [comment] 2020-01-27 11:21
In the previous review/pull request (fyi here https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/15#event-2745126786) we discussed how &m_oDecryptContext wasn't correct.
@pawel-stanek-ml I think confirmed the function declaration was the same in all the MS playready porting kit versions.

I'm wondering if that can be true though, as https://github.com/WebPlatformForEmbedded/OCDM-Playready/commit/f75e0558dd2d1b3f7bb0f7b8bfd12eb10809d647 re-introduces &m_oDecryptContext again. If the function prototypes are the same with Netflix then that shouldn't compile?

@moorthy-bs was trying to remove some of the ifdef stuff like https://github.com/moorthy-bs/OCDM-Playready/commit/a7fa3b9239f33ca51a74ee784f25f637f469c41f#diff-f5cccbfb18fc6a92b33dea1f323d5a98R594. But maybe ultimately it seems like that change is required for some reason?

**Comment by pawel-stanek-ml** [comment] 2020-01-27 11:33
The changes you're referring to were reverted by https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/25. I do not think this PR was needed. @svdmaar ?
We did see netflix broken by change introduced by https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/20 but the only one fix needed - according to my knowledge - was not to check key size (see 449d8cd18721b7710afd58e574beb3901059bfd8 and 6cad9cee3c11623940a807b1bd4e6386d7929683).

**Comment by petegriffin** [comment] 2020-01-27 11:51
https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/25 seems to reintroduce &m_oDecryptContext (see line 591 of the patch)? 

But also https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/25 has some other regressions which make it uncompilable for v3.3 porting kit (see first comment from @moorthy-bs  for more details).

He has some patches to fix it (see here https://github.com/moorthy-bs/OCDM-Playready/commits/master). But it has to introduce some things I thought we had already decided should not be required in the previous review.

**Comment by pawel-stanek-ml** [comment] 2020-01-27 12:02
By "I do not think this PR was needed" I meant that IMO https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/25 shouldn't be merged but maybe there's something I'm not aware of. I suspect it was a quick revert after finding out the commit breaking things for us but as I mentioned the regression was fixed at the very same day with a smaller yet sufficient fix IINM.

**Comment by petegriffin** [comment] 2020-01-27 12:12
Ah I see, yes I agree :) sorry for misunderstanding what you meant. If what you suspect, turns out to be  true, then maybe we could look to revert https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/25?

**Comment by svdmaar** [comment] 2020-01-27 12:27
PR #25 was needed to get Netflix working again. It consist of the code that was originally in the Decrypt method before it broke. One of the things we did try was to remove the "f_cbIV != sizeof(DRM_UINT64)" as was suggested at that time, but that didn't fix it. I won't be able to test it with PR 3.3, but feel free to create a new PR, I will then build and test with Netflix.

**Comment by neeraj-deshpande** [comment] 2020-01-27 13:00
Netflix works with 3dd86a2158d6318d1aafa8ccc78014766f03eed7
With  checks for m_eKeyState  and f_cbIV disabled.
m_eKeyState is not being updated in MediaSessionExt.cpp and Netflix uses  f_cbIV as 24.

**Comment by moorthy-bs** [comment] 2020-01-27 13:55
I think there is an assert for f_cbIV and if m_eKeyState is brought in MediaSessionExt, PR #25 can be reverted.

**Comment by pawel-stanek-ml** [comment] 2020-01-27 14:12
+1 for adding key state updating in the  MediaSessionExt class and revert #25

**Comment by svdmaar** [comment] 2020-01-27 15:09
@neeraj-deshpande , I can also confirm that netflix works with 3dd86a2

**Comment by neeraj-deshpande** [comment] 2020-01-28 09:43
https://github.com/WebPlatformForEmbedded/OCDM-Playready/pull/27

**Comment by pawel-stanek-ml** [comment] 2020-01-28 12:59
Reviewed & merged so all should be happy now.

**Closed by pawel-stanek-ml** 2020-01-28 12:59 UTC
